<center>
    <img src="https://gitlab.com/ibm/skills-network/courses/placeholder101/-/raw/master/labs/module%201/images/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

# **Data Wrangling Lab**

Estimated time needed: **45 to 60** minutes

In this assignment you will be performing data wrangling.

## Objectives

In this lab you will perform the following:

*   Identify duplicate values in the dataset.

*   Remove duplicate values from the dataset.

*   Identify missing values in the dataset.

*   Impute the missing values in the dataset.

*   Normalize data in the dataset.

<hr>

## Hands on Lab

Import pandas module.

In [28]:
import pandas as pd
import numpy as py

Load the dataset into a dataframe.

In [60]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv")
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
2,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
3,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
4,17,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;Multiracial,No,Appropriate in length,Easy

## Finding duplicates

In this section you will identify duplicate values in the dataset.

Find how many duplicate rows exist in the dataframe.

In [61]:
# your code goes here
print(df.duplicated().sum())

154

## Removing duplicates

Remove the duplicate rows from the dataframe.

In [62]:
# your code goes here
df1 = df.drop_duplicates(subset=None, keep=False, inplace=False, ignore_index=False)

Verify if duplicates were actually dropped.

In [63]:
# your code goes here
print(df1.duplicated().sum())

0

## Finding Missing values

Find the missing values for all columns.

In [64]:
# your code goes here
num_vars = df1.columns[df1.dtypes != 'object'] #Seperating categorical and numerical columns in the dataframe for missing values
cat_vars = df1.columns[df1.dtypes == 'object']
df1[cat_vars].isnull().sum().sort_values(ascending=False)

BlockchainIs          2594
BlockchainOrg         2301
MiscTechWorkedWith    2167
SONewContent          1945
SOHowMuchTime         1905
                      ...
Employment               0
SOComm                   0
OpenSourcer              0
Hobbyist                 0
MainBranch               0
Length: 79, dtype: int64

Find out how many rows are missing in the column 'WorkLoc'

In [65]:
# your code goes here
df1['WorkLoc'].isnull()

0        False
1        False
2        False
3        False
4        False
         ...
11547    False
11548    False
11549    False
11550    False
11551    False
Name: WorkLoc, Length: 11305, dtype: bool

## Imputing missing values

Find the  value counts for the column WorkLoc.

In [66]:
# your code goes here
df1['WorkLoc'].isnull().sum()

32

Identify the value that is most frequent (majority) in the WorkLoc column.

In [67]:
#make a note of the majority value here, for future reference
df1['WorkLoc'].value_counts().idxmax()

'Office'

Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [68]:
# your code goes here
df1['WorkLoc'].fillna('Office', inplace=True)

/opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages/pandas/core/generic.py:6245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

After imputation there should ideally not be any empty rows in the WorkLoc column.

Verify if imputing was successful.

In [69]:
# your code goes here
df1['WorkLoc'].isnull().sum()

0

## Normalizing data

There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq".

This makes it difficult to compare the total compensation of the developers.

In this section you will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq'.

Once this column is ready, it makes comparison of salaries easy.

<hr>

List out the various categories in the column 'CompFreq'

In [70]:
# your code goes here
df1["CompFreq"].unique()

array(['Yearly', 'Monthly', 'Weekly', nan], dtype=object)

Create a new column named 'NormalizedAnnualCompensation'. Use the hint given below if needed.

Double click to see the **Hint**.

<!--

Use the below logic to arrive at the values for the column NormalizedAnnualCompensation.

If the CompFreq is Yearly then use the exising value in CompTotal
If the CompFreq is Monthly then multiply the value in CompTotal with 12 (months in an year)
If the CompFreq is Weekly then multiply the value in CompTotal with 52 (weeks in an year)

-->

In [73]:
# your code goes here
df1.loc[df1['CompFreq'] == 'Yearly', 'NormalizedAnnualCompensation'] = 1 * df1['CompTotal']
df1.loc[df1['CompFreq'] == 'Monthly', 'NormalizedAnnualCompensation'] = 12 * df1['CompTotal']
df1.loc[df1['CompFreq'] == 'Weekly', 'NormalizedAnnualCompensation'] = 52 * df1['CompTotal']

df1[['CompTotal', 'CompFreq', 'NormalizedAnnualCompensation']].head(20)

    CompTotal CompFreq  NormalizedAnnualCompensation
0     61000.0   Yearly                       61000.0
1    138000.0   Yearly                      138000.0
2     90000.0   Yearly                       90000.0
3     29000.0  Monthly                      348000.0
4     90000.0   Yearly                       90000.0
5      9500.0  Monthly                      114000.0
6      3000.0  Monthly                       36000.0
7    103000.0   Yearly                      103000.0
8     69000.0   Yearly                       69000.0
9      8000.0  Monthly                       96000.0
10     7000.0  Monthly                       84000.0
11   114000.0   Yearly                      114000.0
12     2000.0   Weekly                      104000.0
13    22000.0   Weekly                     1144000.0
14    96000.0  Monthly                     1152000.0
15   156000.0   Yearly                      156000.0
16    18000.0   Yearly                       18000.0
17     6400.0  Monthly                       76800.0
18     5000.0  Monthly                       60000.0
19   400000.0   Yearly                      400000.0

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer\&utm_source=Exinfluencer\&utm_content=000026UJ\&utm_term=10006555\&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2021-01-01\&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264\&cm_mmca1=000026UJ\&cm_mmca2=10006555\&cm_mmca3=M12345678\&cvosrc=email.Newsletter.M12345678\&cvo_campaign=000026UJ).